apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    app: db
spec:
  containers:
  - name: db
    image: mysql:5.6
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: Aula@1234
    ports:
    - containerPort: 3306